# fly.toml app configuration file generated for vocode-golang on 2023-11-20T18:06:43-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vocode-golang"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

# Cause No-Docker projects (like this one) use Packate to "magically guess" the command to run;
# AND that we have multiple main.main() in our project, we gotta be explicit here.
# https://community.fly.io/t/multiple-commands-in-a-go-application/1677/4
[build.args]
  BP_GO_TARGETS = "./cmd/twilio"

[env]
  PORT = "8080"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
